[env:array_body]
board = uno
platform = atmelavr
framework = arduino
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_speed = 115200
build_flags = 
	-D ARRAYBODY
	-std=c++17
build_unflags =
	-std=gnu++1z
	-std=c++11
	-std=c++14
	-std=c++20
	-std=c++2a
lib_deps=
	MENU=symlink://../../../AM26.03.25
	; "streamFlow"=symlink://../../../Metal/streamFlow/
	https://github.com/neu-rah/streamFlow.git
	https://github.com/neu-rah/tinyTimeUtils.git

[env:strtext_body]
board = uno
platform = atmelavr
framework = arduino
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_speed = 115200
build_flags = 
	-D STRTEXT
	-std=c++17
build_unflags =
	-std=gnu++1z
	-std=c++11
	-std=c++14
	-std=c++20
	-std=c++2a
lib_deps=
	MENU=symlink://../../../AM26.03.25
	; "streamFlow"=symlink://../../../Metal/streamFlow/
	https://github.com/neu-rah/streamFlow.git
	https://github.com/neu-rah/tinyTimeUtils.git

[env:ctext_body]
board = uno
platform = atmelavr
framework = arduino
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_speed = 115200
build_flags = 
	-D CTEXT
	-std=c++17
build_unflags =
	-std=gnu++1z
	-std=c++11
	-std=c++14
	-std=c++20
	-std=c++2a
lib_deps=
	MENU=symlink://../../../AM26.03.25
	; "streamFlow"=symlink://../../../Metal/streamFlow/
	https://github.com/neu-rah/streamFlow.git
	https://github.com/neu-rah/tinyTimeUtils.git

[env:iitem_body]
board = uno
platform = atmelavr
framework = arduino
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_speed = 115200
build_flags = 
	-D IITEM
	-std=c++17
build_unflags =
	-std=gnu++1z
	-std=c++11
	-std=c++14
	-std=c++20
	-std=c++2a
lib_deps=
	MENU=symlink://../../../AM26.03.25
	; "streamFlow"=symlink://../../../Metal/streamFlow/
	https://github.com/neu-rah/streamFlow.git
	https://github.com/neu-rah/tinyTimeUtils.git
