[env:native]
platform = native
build_flags = 
	-DMENU_DEBUG
	-g
	-std=c++17
	-Wno-comment
debug_build_flags = -O0 -ggdb3 -g3 -no-pie 
	-DMENU_DEBUG
	-Wno-comment
lib_deps=
	MENU=symlink://../../../AM5
	HAPI=symlink://../../../../IOP/HAPI
	OneData=symlink://../../../../IOP/OneData
	OneList=symlink://../../../../IOP/OneList
	OneOut=symlink://../../../../IOP/OneOutput
	https://github.com/neu-rah/tinyTimeUtils.git@^1.1.5
	; https://github.com/InternetOfPins/HAPI@^0.3.8
	; https://github.com/InternetOfPins/OneData@^0.1.7
	; https://github.com/InternetOfPins/OneList@^0.0.8

[env:uno]
board = uno
platform = atmelavr
framework = arduino
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_speed = 115200
build_flags = 
	-std=c++17
build_unflags =
	-std=c++11
	-std=c++14
	-std=c++20
	-std=c++2a
	-std=gnu++1z
lib_deps=
	MENU=symlink://../../../AM5
	https://github.com/neu-rah/streamFlow.git
	https://github.com/neu-rah/tinyTimeUtils.git@^1.1.5
	https://github.com/InternetOfPins/HAPI@^0.3.7
	https://github.com/InternetOfPins/OneData@^0.1.7
	https://github.com/InternetOfPins/OneList@^0.0.8
