[env:native]
platform = native
build_flags = 
	-DMENU_DEBUG
	-g
	-std=c++17
debug_build_flags = -O0 -ggdb3 -g3 -no-pie 
lib_deps=
	MENU=symlink://../../../AM5
  ; streamFlow=symlink://../../../../Metal/streamFlow/
	https://github.com/neu-rah/streamFlow.git
	https://github.com/neu-rah/tinyTimeUtils.git

